# @param customeName allows to set a custom resource name in k8s
## Defaults to {{ .Release.Name }}-{{ .Chart.Name }}

customName: 'laminar-job-control-api'


# @param replicaCount Number of Nginx replicas to deploy
replicaCount: 2


## Settings for NGINX image

## @param image.name Nginx image name to use
## @param image.tag NGinx image tag to use
image:
  name: nginx
  tag:  "1.27.0"


## Settings for NGINX container securiotyContext

## @param securityContext.enabled
## @param securityContext.runAsUser
## @param securityContext.fsGroup 
securityContext:
  enabled:  true
  runAsUser: 0
  fsGroup: 2000

## NGINX container ports
##
## @param containerPorts.http
containerPorts:
  http: 80

## Settings for NGINX services
## Services is a map with the following schema

## @param services["*"] The type of service in front of the NGINX pods
## @param services["*"] The port where the service is receiving request

services:  
  svc2:
    type: NodePort
    port: 30007
  svc1:
    type: ClusterIP
    port: 80


