apiVersion: apps/v1
kind: Deployment
metadata:
  name:    {{ include "templating-deep-dive.fullname" . }}  # local-nginx-nginx
  labels:
    {{ include "templating-deep-dive.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ .Chart.Name }}
      release:  {{ .Release.Name }}

  template:
    metadata:
      labels:
        app:  {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.containerPorts.http }}
      

