{{- range $key, $svc := (.Values.services | default dict ) }}
---
# The value of the .: {{ . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "templating-deep-dive.fullname" $ }}-{{ $key }}
  labels: 
    {{- include "templating-deep-dive.selectorLabels" $ | nindent 3 }}
spec:
  type: {{ .type }}
  selector: 
    {{- include "templating-deep-dive.selectorLabels" $ | nindent 5 }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ $.Values.containerPorts.http }}

{{- end }}